# Intro python data science
## Práctica 04: numpy ndarray

Vamos a ver cómo:
* Punto 1: Crear ndarrays en python
* Punto 2: Operar entre columnas
* Punto 3: Seleccionar elementos

# Punto 1:

In [ ]:
# importar numpy as np

In [ ]:
import numpy as np

In [ ]:
# crear lista con numeros primos

In [ ]:
primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [ ]:
primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [ ]:
# crear array a partir de lista

In [ ]:
arr_primos = np.array(primos)

In [ ]:
arr_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [ ]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy

In [ ]:
ceros = np.zeros(5)

In [ ]:
ceros

array([0., 0., 0., 0., 0.])

In [ ]:
# crear arrays con números

In [ ]:
numeros = np.array([10, 20, 30, 40, 50])

In [ ]:
numeros

array([10, 20, 30, 40, 50])

In [ ]:
# array con numeros sucesivos

In [ ]:
sucesivos = np.arange(1,11)

In [ ]:
sucesivos

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(1, 21)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# haciendo un reshape para dos dimensiones

In [ ]:
matriz = arr.reshape(4,5)

In [ ]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Punto 2:

In [ ]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([5, 4, 3, 2, 1])

In [ ]:
suma = a + b

In [ ]:
suma

array([6, 6, 6, 6, 6])

In [ ]:
multiplicacion = a * b

In [ ]:
multiplicacion

array([5, 8, 9, 8, 5])

In [ ]:
# multiplicar por 100

In [ ]:
a * 100

array([100, 200, 300, 400, 500])

In [ ]:
# resta entre arrays

In [ ]:
a - b

array([-4, -2,  0,  2,  4])

In [ ]:
# cuidado con la división entre cero

In [ ]:
x = np.array([10, 20, 30])

In [ ]:
y = np.array([2, 0, 5])

In [ ]:
x / y

/tmp/ipykernel_1771/3016948717.py:1: RuntimeWarning: divide by zero encountered in divide
  x / y


array([ 5., inf,  6.])

In [ ]:
# métodos asociados a estadística

In [ ]:
# suma

In [ ]:
a.sum()

np.int64(15)

In [ ]:
# promedio

In [ ]:
a.mean()

np.float64(3.0)

In [ ]:
# varianza

In [ ]:
a.var()

np.float64(2.0)

In [ ]:
# como ordenar un np array

In [ ]:
desordenado = np.array([3, 2, 0, 1, 10, -1])

In [ ]:
# orden ascendente: de menor a mayor

In [ ]:
np.sort(desordenado)

array([-1,  0,  1,  2,  3, 10])

In [ ]:
# orden descendente: de mayor a menor

In [ ]:
np.sort(desordenado)[::-1]

array([10,  3,  2,  1,  0, -1])

# Punto 3:

In [ ]:
# Como seleccionar elements

In [ ]:
datos = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [ ]:
datos

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# Seleccionar un elemento

In [ ]:
datos[1,1]

np.int64(50)

In [ ]:
datos[2,2]

np.int64(90)

In [ ]:
# seleccionar el primer elemento

In [ ]:
datos[0,0]

np.int64(10)

In [ ]:
# seleccionar algún otro elemento

In [ ]:
datos[0,2]

np.int64(30)

In [ ]:
# Seleccionar varios elementos

In [ ]:
datos[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# seleccionar por fila

In [ ]:
datos[1]

array([40, 50, 60])

In [ ]:
# seleccionar por columna

In [ ]:
datos[:,1]

array([20, 50, 80])

In [ ]:
# Utilizar filter

In [ ]:
numeros = np.array([5, 12, 18, 25, 30, 8])

In [ ]:
numeros

array([ 5, 12, 18, 25, 30,  8])

In [ ]:
# condición mayores de 15

In [ ]:
numeros > 15

array([False, False,  True,  True,  True, False])

In [ ]:
# conidicion para menores de 20

In [ ]:
numeros < 20

array([ True,  True,  True, False, False,  True])

In [ ]:
# filtrar menores de 20

In [ ]:
numeros[numeros < 20]

array([ 5, 12, 18,  8])

In [ ]:
# filtrar mayores o iguales a 20

In [ ]:
numeros[numeros >= 20]

array([25, 30])